### ISSUE TITLE
Budyko space doesn't work

### ISSUE THREAD

**Issue by Francesco-Grossi** [stineb/rsofundemo#11]
Budyko space present value of AET higher than 1.
To run the script, insert the driver data founded on zenodo in data-raw

**Comment by stineb** [comment]
What script should be run?

**Comment by Francesco-Grossi** [comment]
01_budyko curve
________________________________
Da: Benjamin Stocker ***@***.***>
Inviato: martedì 27 febbraio 2024 10:12
A: stineb/rsofundemo ***@***.***>
Cc: Francesco Grossi ***@***.***>; Author ***@***.***>
Oggetto: Re: [stineb/rsofundemo] Budyko space doesn't work (Issue #11)

Non si ricevono spesso messaggi di posta elettronica da ***@***.*** Informazioni sul perché è importante<https://aka.ms/LearnAboutSenderIdentification>

What script should be run?

**Comment by stineb** [comment]
This seems obsolete now. File no longer exists.
