### ISSUE TITLE
test fail

### ISSUE THREAD

**Issue by stineb** [stineb/rsofundemo#12]
@FrancescoGrossi-unimi , when making a pull request (PR), you should see the results of the continuous integration (CI) tests run on the repo after the CI. Currently, the test fails, see below. Make sure to look at these results and resolve any error. I have now merged your PR despite the test fail. In the future, please make sure to resolve these errors.

```
Quitting from lines 10-16 [unnamed-chunk-1] (p_model_multisite.Rmd)
--------------------------------------------------------------------------------
Error in `map()`:
ℹ In index: 1.
Caused by error in `render_rmarkdown()`:
! Failed to render RMarkdown
Caused by error:
! in callr subprocess.
Caused by error:
! there is no package called 'dplyr'
Backtrace:
    ▆
 1. └─base::library(dplyr)
Execution halted
Error: Process completed with exit code 1.
```

**Comment by Francesco-Grossi** [comment]
It says that the error is in the library loading of the p_model_multisite in vignette folder, which is very strange but I'll try to solve it
