### ISSUE TITLE
Get multisite workflow to run 

### ISSUE THREAD

**Issue by stineb** [stineb/rsofundemo#2]
Thanks for the great amount of work already achieved @FrancescoGrossi-unimi  and to Jaideep for sharing his workflow. 

I marked a few points with `xxx` in the file `vignettes/rsofun_multisite_fdk.R` (see latest commit in `stineb/rsofundemo`). Please have a look at them. A few general points:

- [x] We only use the daily forcing time series as prepared in the FluxDataKit repository, not the mid-day (3-hour) average which is additionally prepared for P-hydro in Jaideep's workflow. Have a look at what Koen put together for a multisite workflow in FluxDataKit:

- https://github.com/geco-bern/FluxDataKit/blob/main/analysis/02_batch_format_rsofun_drivers.R
- https://github.com/geco-bern/FluxDataKit/blob/main/analysis/03_screen_rsofun_data.R
- https://github.com/geco-bern/FluxDataKit/blob/main/analysis/06_p-model_run.R

- [x] Eventually, you can write up your workflow in such a way that others can easily adopt it and that it's visible on the rsofundemo website. For this, please (eventually) make it into a vignette and document/explain each step.

**Comment by stineb** [comment]
Some remaining points:

- [x] Use README to describe what workflow/analysis step can be found where.
- [x] Specify all paths with `here::here()`
- [x] image files go into `fig/`
- [x] data files go into `data/` (files produced by workflows of repository) or `data-raw/` (external files that used as inputs to workflows of repository

See [out turorial](https://geco-bern.github.io/agds/gettingstarted.html#wspmgmt) and [this](https://geco-bern.github.io/agds/openscience.html#project-structure-1) for workspace management, git project organisation and dealing with paths in a project.

**Comment by stineb** [comment]
@FrancescoGrossi-unimi 
Are these points open or closed. If they're completed, please tick them off.

**Comment by Francesco-Grossi** [comment]
I'll change the readme the others are completed, I'm not able to tick them off

**Comment by stineb** [comment]
@FrancescoGrossi-unimi I've invited you to the repo. Like this, you should be able to tick them off. Please do so if they're done. Thanks.

**Comment by Francesco-Grossi** [comment]
now it works thank  you
