### ISSUE TITLE
multisite vignette gone?

### ISSUE THREAD

**Issue by stineb** [stineb/rsofundemo#8]
The file `vignette/p_model_multisite.Rmd` is no longer in your fork, @FrancescoGrossi-unimi . A new vignette is there now, called `p_model_use.Rmd`. But that's the name of the vignette we have in rsofun. What is where now? Please implement the demo of the multi-site workflow as a vignette called `vignette/p_model_multisite.Rmd`. 

In contrast, the `README.md` should not contain the workflow demo. It is not executable in R. Please use the README just for describing what is shown in what vignette (and installation instructions, as you have it).

**Comment by Francesco-Grossi** [comment]
I renamed the vignette al get rid of the code in README
